name: MD2PDF

on: push

jobs:
  convert_via_pandoc:
    name: Convert via Pandoc
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: maxheld83/pandoc@v2
        with:
          args: "--standalone --output=ir-2019.pdf *.md"
      - uses: actions/upload-artifact@master
        with:
          name: ir-2019
          path: ir-2019.pdf
